language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t kimasx/docker-sandbox -f Dockerfile.dev .

script:
  - docker run -e CI=true kimasx/docker-sandbox npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-frontend-app"
  env: "DockerFrontendApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-794944452292"
  bucket_path: "docker-frontend-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY